### ISSUE TITLE
XMFA file format

### ISSUE THREAD

**Issue by sebasso** [marbl/parsnp#29] opened 2017-02-15 17:11 UTC
After running parsnp with your test-mers data i get the parsnp.xmfa file.
Before each fasta sequence there is a header with some information like this:
 ">1:57-25332 + cluster2 s1:p57"
Where the first number denotes the sequence ID defined longer up in the file
the following after ":" is sequence start to("-") sequence end, "+" cluster-name combined
with cluster-number. I was wondering what "s1" and "p57" means?
It looks the number in front of the ":" _always_ is the same whilst the number after ":p" _always_
is the same as the start position of thats sequence LCB. 

Will this always be the case?

Runned with your mers data like this:
./parsnp -g mers49/refs/EMC_2012.gbk -d /mers49/mers49 -p 32 

[fastaheaders.txt](https://github.com/marbl/parsnp/files/777781/fastaheaders.txt)

**Comment by bkille** [comment] 2020-06-20 18:21
Duplicate of #31

**Closed by bkille** 2020-06-20 18:21 UTC
