### ISSUE TITLE
Not incorporating all files

### ISSUE THREAD

**Issue by LindsayLiang** [marbl/parsnp#32] opened 2017-03-18 21:49 UTC
I'm running parsnp on a directory containing 575 strains, and only 573 of them are being incorporated into the analysis.  I've used the -c argument to dictate that my directory is curated.  The command I used was:

parsnp -c -v  -r /Scratch.NFS/.../EGDe.fasta  -d /Scratch.NFS/.../Cat/ -p 24 -o ParsnpTest

Any thoughts?

**Comment by thorellk** [comment] 2018-08-06 07:14
I have the same issue

**Comment by bkille** [comment] 2020-06-20 18:45
Any chance you could attach the files? There is a good chance parsnp 1.2 skipped them due to some parsing error. Version 1.5 has fixed many of these errors, so please try again and let me know if the issue persists.

**Comment by bkille** [comment] 2020-06-20 19:00
Duplicate of #6

**Closed by bkille** 2020-06-20 19:00 UTC
